# Generated by Django 3.2.9 on 2022-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_buyer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0257425689', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
