# Generated by Django 4.1 on 2022-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20220810_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquantity',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
