# Generated by Django 3.2.9 on 2022-06-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_buyer_customer'),
        ('orders', '0002_orders_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
    ]
