# Generated by Django 3.2.9 on 2022-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered_time',
            field=models.DateTimeField(),
        ),
    ]
