# Generated by Django 3.2.9 on 2022-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_delivered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
