# Generated by Django 3.2.9 on 2022-08-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
