# Generated by Django 3.2.9 on 2022-08-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_price_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='d1elivered_time',
        ),
    ]
