# Generated by Django 4.1 on 2022-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orders_d1elivered_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
